<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="0" ignored="0" total="2" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="N11 Test Suite" duration-ms="437" started-at="2018-04-29T18:34:46Z" finished-at="2018-04-29T18:34:46Z">
    <groups>
    </groups>
    <test name="LoginTestTEST" duration-ms="437" started-at="2018-04-29T18:34:46Z" finished-at="2018-04-29T18:34:46Z">
      <class name="tests.LoginTests">
        <test-method status="PASS" signature="setUp()[pri:0, instance:tests.LoginTests@4501b7af]" name="setUp" is-config="true" duration-ms="0" started-at="2018-04-29T18:34:46Z" finished-at="2018-04-29T18:34:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="invalidLoginTest_InvalidUserNameInvalidPasswordGOINGFORWARD(java.lang.String)[pri:0, instance:tests.LoginTests@4501b7af]" name="invalidLoginTest_InvalidUserNameInvalidPasswordGOINGFORWARD" duration-ms="375" started-at="2018-04-29T18:34:46Z" description="Invalid Login Scenario with wrong username and password." data-provider="browser-provider" finished-at="2018-04-29T18:34:46Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[TABLETS]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- invalidLoginTest_InvalidUserNameInvalidPasswordGOINGFORWARD -->
        <test-method status="PASS" signature="handleException()[pri:0, instance:tests.LoginTests@4501b7af]" name="handleException" is-config="true" duration-ms="0" started-at="2018-04-29T18:34:46Z" finished-at="2018-04-29T18:34:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- handleException -->
        <test-method status="PASS" signature="handleException()[pri:0, instance:tests.LoginTests@4501b7af]" name="handleException" is-config="true" duration-ms="0" started-at="2018-04-29T18:34:46Z" finished-at="2018-04-29T18:34:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- handleException -->
        <test-method status="PASS" signature="invalidLoginTest_InvalidUserNameInvalidPasswordGOINGFORWARD(java.lang.String)[pri:0, instance:tests.LoginTests@4501b7af]" name="invalidLoginTest_InvalidUserNameInvalidPasswordGOINGFORWARD" duration-ms="0" started-at="2018-04-29T18:34:46Z" description="Invalid Login Scenario with wrong username and password." data-provider="browser-provider" finished-at="2018-04-29T18:34:46Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[MICE]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- invalidLoginTest_InvalidUserNameInvalidPasswordGOINGFORWARD -->
      </class> <!-- tests.LoginTests -->
    </test> <!-- LoginTestTEST -->
  </suite> <!-- N11 Test Suite -->
</testng-results>
